config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'
  get 'about', to: 'pages#about'
  #get 'articles' to: 'articles#new'
  
  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    validates :title, presence: true
    validates :description, presence: true
    validates :user_id, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name

end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles, dependent: :destroy
    before_save { self.email = email.downcase }

    validates :username, presence: { case_sensitive: false}, uniqueness: true, 
    length: { minimum: 3, maximum: 25}

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 105},
    uniqueness: { case_sensitive: false },
    format: { with: VALID_EMAIL_REGEX }

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in? 
      flash[:danger] = "You must be logged in to perform that action."
      redirect_to root_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :set_article, only: [:edit, :update, :show, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def index
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end

    def new
        @article = Article.new
    end

    def edit
        
    end

    def create 
        #debugger
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:success] = "Article was successfully created."
            redirect_to article_path(@article)
        else 
            render 'new'
        end
    end

    def update
        if @article.update(article_params)
            flash[:success] = "Article was successfully updated."
            redirect_to article_path(@article)
        else
            render 'edit'
        end
    end

    def show 
        
    end

    def destroy  
        @article.destroy
        flash[:danger] = "Article was successfully deleted."
        redirect_to articles_path
    end

    private 
    def set_article
        @article = Article.find(params[:id])
    end

    def article_params 
        params.require(:article).permit(:title, :description)
    end

    def require_same_user 
        if current_user != @article.user && !current_user.admin?
            flash[:danger] = "You can only edit or delete your own articles."
            redirect_to root_path
        end
    end 

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
        @categories = Category.all
    end

    def new 
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:success] = "Category created successfully!"
            redirect_to categories_path
        else   
            render 'new'
        end
    end

    def show 

    end

    private
    def category_params
        params.require(:category).permit(:name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


    def home
        redirect_to articles_path if logged_in?
    end

    def about 

    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new

    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "You have successfully logged in."
            redirect_to user_path(user)
        else
            flash.now[:danger] = "There was something wrong with your login credentials."
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "You have logged out."
        redirect_to root_path
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    before_action :requre_admin, only: [:destroy]

    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end

    def new 
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:success] = "Welcome to the Alpha Blog #{@user.username}"
            redirect_to user_path(@user)
        else
            render 'new'
        end
    end

    def edit
        
    end

    def show
        
        @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        flash[:danger] = "User and all articles have been deleted."
        redirect_to users_path
    end

    def update
        
        if @user.update(user_params)
            flash[:success] = "You successfully updated your account."
            redirect_to articles_path
        else
            render 'edit'
        end
    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
    def set_user
        @user = User.find(params[:id])
    end

    def require_same_user
        if current_user != @user && !current_user.admin?
            flash[:danger] = "You can only edit your own account."
            redirect_to root_path
        end
    end

    def requre_admin
        if logged_in? && !current_user.admin?
            flash[:danger] = "Only admin users can perform that action."
            redirect_to root_path
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = {size: 150})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: 'rounded-circle')
    end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
    <div class="row">
        <div class="col-md-12">
            <div class="card mb-5 text-center">
                <div class="card-body">
                    <div class="card-title">
                        <%= link_to article.title, article_path(article) %>
                    </div>
                    <p class="card-text content">
                        <%= truncate(article.description, length: 100) %>
                        <div class="card-meta-details">
                            <small>Created by: <%= article.user.username if article.user %>, <%= time_ago_in_words(article.created_at) %> ago, last updated: <%= time_ago_in_words(article.updated_at) %></small>
                        </div>
                    </p>
                    <% if logged_in? && (current_user == article.user || current_user.admin?) %>
                    <div class="article-actions">
                        <%= link_to 'Delete this article', article_path(article), method: :delete, data: {confirm: "Are you sure you want to delete this article?"}, class: "btn btn-danger btn-sm" %>
                        <%= link_to 'Edit this article', edit_article_path(article), class: "btn btn-primary btn-sm" %>
                    </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
    <% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
    <div class="col-12">
        <%= form_for(@article, :html => {class: "form", role: "form"}) do |f| %>
            <div class="form-group">
                <%= f.label :title, class: "label-title" %>
                <%= f.text_field :title, class: "form-control"%>
            </div>
            <div class="form-group">
                <%= f.label :description, class: "label-title" %>
                <%= f.text_area :description, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= f.submit class: "btn btn-primary mb-2" %>
            </div>
        <% end %>

        [ <%= link_to 'Cancel request and go back to article listing', articles_path, class: "go_back_link" %> ]
    </div>
</div>

app/views/articles/edit.html.erb
<div class="container">
    <h1 class="title">Edit Article</h1>
    <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div class="container">
<h1 class="title">List of all articles</h1>
<div align="center">
    <%= will_paginate %>
</div>
    <%= render 'article', obj: @articles %>
<div align="center">
    <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<div class="container">
    <h1 class="title">Create an Article</h1>
    <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<h2 align="center"><%= @article.title %></h2>
<div class="container content">
    <ul class="listing">
            <div class="row text-center">
                <div class="card" style="width: 18rem">
                    <img><%= link_to(gravatar_for(@article.user), user_path(@article.user)) if @article.user %></img>
                    <div class="card-body">
                        <div class="card-title"><%= link_to(@article.user.username, user_path(@article.user)) if @article.user %></div>
                        <div><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></div>
                    </div>
                </div>
            </div>
        </ul>
    <%= @article.description %>
</div>
<div class="container text-center" style="margin-top: 25px">
    <hr>
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
        <%= link_to 'Delete this article', article_path(@article), method: :delete, data: {confirm: "Are you sure you want to delete this article?"}, class: "btn btn-danger btn-sm" %>
        <%= link_to 'Edit this article', edit_article_path(@article), class: "btn btn-success btn-sm" %> 
    <% end %>
    <%= link_to 'Back to article listing', articles_path, class: "btn btn-primary btn-sm" %>
</div>

app/views/categories/index.html.erb
<div class="container">
    <h1 class="title">List of all categories</h1>
    <% @categories.each do |category| %>
    <ul class="listing">
        <div class="row text-center">
                <div class="card" style="width: 18rem">
                    <div class="card-body">
                        <div class="card-title"><%= link_to "#{category.name}", category_path(category) %></div>
                    </div>
                </div>
            </div>
    </ul>
    <% end %>
</div>

app/views/categories/new.html.erb
<div class="container">
    <h1 class="title">Create new category</h1>
    <%= render 'shared/errors', obj: @category %>

    <div class="row">
        <div class="col-12">
            <%= form_for(@category, :html => {class: "form", role: "form"}) do |f| %>
                <div class="form-group">
                    <%= f.label :name, class: "label-title" %>
                    <%= f.text_field :name, class: "form-control"%>
                </div>
                <div class="form-group">
                    <%= f.submit "Create category", class: "btn btn-primary mb-2" %>
                </div>
            <% end %>

            [ <%= link_to 'Cancel request and go back to article listing', articles_path, class: "go_back_link" %> ]
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer text-center">
    <small>Copyright &copy; <a href="#"> Blog App</a> by <a href="#">Andrea L.</a></small>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
    <div class="col-12">
        <div class="container">
            <%= flash.each do |name, msg| %>
                <div class='alert alert-<%="#{name}" %>'>
                    <a href="#" class="close" data-dismiss="alert">&#215;</a>
                    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
    <%= link_to 'Alpha Blog', root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      <li class="nav-item">
          <%= link_to 'About', about_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Articles', articles_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Users', users_path, class: "nav-link"%>
        </li>
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Article Actions
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Create Article', new_article_path, class: "dropdown-item"%>
            </div>
          </li>
        <% end %>
        <% if logged_in? %>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Profile <%= "Admin" if current_user.admin? %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'View Profile', user_path(current_user), class: "dropdown-item"%>
              <%= link_to 'Edit Profile', edit_user_path(current_user), class: "dropdown-item"%>
              <%= link_to 'Logout', logout_path, method: :delete, class: "dropdown-item"%>
            </div>
          </li>
        <% else %>
        <li class="nav-item">
          <%= link_to 'Login', login_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Register', signup_path, class: "nav-link"%>
        </li>
        <% end %>
      </ul>
      <!--
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
      -->
      
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <!--<%= debug(params) if Rails.env.development? %>-->
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Page</h1>
<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<section class="landing-page">
    <div class="container">
        <div class="jumbotron jumbotron-fluid text-center">
            <h1 class="display-4">ALPHA BLOG</h1>
            <p class="lead">This is a simple blog app build with Rails.</p>
            <hr class="my-4">
            <%= link_to 'Sign Up', signup_path, class: "btn btn-primary btn-lg btn-landing-page" %>
        </div>
    </div>
</section>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
    <div class="col">
        <div class="card text-white bg-danger">
            <div class="card-body">
                <h5 class="card-title">
                <%= pluralize(obj.errors.count, "error") %> prohibited this article from being saved:
                </h5>
                <div class="card-body">
                    <ul>
                        <% obj.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class="container">
    <div class="row">
        <div class="col-12">
            <%= form_for(@user, :html => {class: "form", role: "form"}) do |f| %>
                <div class="form-group">
                    <%= f.label :username, class: "label-title" %>
                    <%= f.text_field :username, class: "form-control"%>
                </div>
                <div class="form-group">
                    <%= f.label :email, class: "label-title" %>
                    <%= f.email_field :email, class: "form-control" %>
                </div>
                <div class="form-group">
                    <%= f.label :password, class: "label-title" %>
                    <%= f.password_field :password, class: "form-control" %>
                </div>
                <div class="form-group">
                    <%= f.submit(@user.new_record? ? "Sign Up" : "Update", class: "btn btn-primary mb-2") %>
                </div>
            <% end %>

            [ <%= link_to 'Cancel request and go back to article listing', articles_path, class: "go_back_link" %> ]
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<div class="container">
    <h1 class="title">Edit Your Account</h1>
    <%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="container">
    <h1 class="title">View All Users</h1>
    <%= will_paginate %>
    <% @users.each do |user| %>
        <ul class="listing">
            <div class="row text-center">
                <div class="card" style="width: 18rem">
                    <img><%= link_to gravatar_for(user), user_path(user) %></img>
                    <div class="card-body">
                        <div class="card-title"><%= link_to user.username, user_path(user) %></div>
                        <div><small><%= pluralize(user.articles.count, "article") if user.articles %></small></div>
                        <% if logged_in? && current_user.admin? %>
                            <li><%= link_to "Delete this user", user_path(user), method: :delete, data: { confirm: "Are you sure you want to delete the user and all their articles?"} %></li>
                        <% end %>
                    </div>
                </div>
            </div>
        </ul>
    <% end %>
    <%= will_paginate %>
</div>

app/views/users/new.html.erb
<div class="container">
    <%= render 'shared/errors', obj: @user %>
    <h1 class="title">Sign Up for Alpha Blog</h1>

<div class="row">
    <div class="col-12">
        <%= form_for(@user, :html => {class: "form", role: "form"}) do |f| %>
            <div class="form-group">
                <%= f.label :username, class: "label-title" %>
                <%= f.text_field :username, class: "form-control"%>
            </div>
            <div class="form-group">
                <%= f.label :email, class: "label-title" %>
                <%= f.email_field :email, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= f.label :password, class: "label-title" %>
                <%= f.password_field :password, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= f.submit "Sign Up", class: "btn btn-primary mb-2" %>
            </div>
        <% end %>

        [ <%= link_to 'Cancel request and go back to article listing', articles_path, class: "go_back_link" %> ]
    </div>
</div>

</div>

app/views/users/show.html.erb
<div class="container">
    <h1 class="title">Welcome to <%= @user.username %>'s page</h1>
    <div class="row">
        <div class="col-12 center">
            <%= gravatar_for @user %>
        </div>  
    </div>
    <h4><%= @user.username %>'s articles</h4>
    <div class="center">
        <%= will_paginate @user_articles %>
    </div>
    <%= render 'articles/article', obj: @user_articles %>
    <div class="center">
        <%= will_paginate @user_articles %>
    </div>
</div>